### ISSUE TITLE
Swift Installation on DOMJudge Host

### ISSUE THREAD

**Issue by ashihCT** [DOMjudge/domjudge#518]
I looked at Issue #236 for initial guidance, but the solution seems incomplete.

I modified the `dj_make_chroot` with the following commands. I verified the tar is downloaded and unarchived. 
```
# Upgrade the system, and install/remove packages as desired
chroot "$CHROOTDIR" /bin/sh -c "apt-get update && apt-get dist-upgrade"
chroot "$CHROOTDIR" /bin/sh -c "apt-get clean"
chroot "$CHROOTDIR" /bin/sh -c "apt-get install $INSTALLDEBS"
wget https://swift.org/builds/swift-4.2.2-release/ubuntu1804/swift-4.2.2-RELEASE/swift-4.2.2-RELEASE-ubuntu18.04.tar.gz -O "$CHROOTDIR/usr/lib/swift-4.2.2-RELEASE-ubuntu18.04.tar.gz"
cd "$CHROOTDIR/usr/lib/"
tar xzf swift-4.2.2-RELEASE-ubuntu18.04.tar.gz
chroot "$CHROOTDIR" /bin/sh -c "chmod 755 /usr/lib/swift-4.2.2-RELEASE-ubuntu18.04"
chroot "$CHROOTDIR" /bin/sh -c "chown -R root:root /usr/lib/swift-*"
chroot "$CHROOTDIR" /bin/sh -c "export PATH=/usr/lib/swift-4.2.2-RELEASE-ubuntu18.04/usr/bin:$PATH"
```
For some reason when I want to manually check it inside the CHROOT by mounting:
```
mount -t proc proc "$CHROOTDIR/proc"
mount -t sysfs sysfs "$CHROOTDIR/sys"
mount --bind /dev/pts "$CHROOTDIR/dev/pts"
chroot "$CHROOTDIR"
```
If I do, `echo $PATH`, it has not been added. If I manually run `export PATH=/usr/lib/swift-4.2.2-RELEASE-ubuntu18.04/usr/bin:$PATH`, it recognizes the command `swift`.

What am I doing wrong?

### Your environment
> Include details about your installation here. 
> - DOMjudge version 6.0.3
> - AWS Ubuntu 18.04
> - Apache 2

**Comment by nickygerritsen** [comment]
The command `chroot "$CHROOTDIR" /bin/sh -c "export PATH=/usr/lib/swift-4.2.2-RELEASE-ubuntu18.04/usr/bin:$PATH"` will not save the path inside the chroot, only for that shell, which is immediately stopped... I'm actually not sure what the best way is to update the path in the chroot, maybe others know.

If you want a 'quick and dirty' solution, instead of running `swift` in the DOMjudge executable script, run `/usr/lib/swift-4.2.2-RELEASE-ubuntu18.04/usr/bin/swift`.

**Comment by ashihCT** [comment]
Here is my execution script:

```
#!/bin/sh
DEST="$1" ; shift
MEMLIMIT="$1" ; shift
MAINSOURCE="${ENTRY_POINT:-$1}"

# Check syntax
/usr/lib/swift-4.2.2-RELEASE-ubuntu18.04/usr/bin/swiftc "$@"
EXITCODE=$?
[ "$EXITCODE" -ne 0 ] && exit $EXITCODE
rm -f -- *.swift

# Check if entry point is valid
if [ ! -r "$MAINSOURCE" ]; then
    >&2 echo "error: main source file '$MAINSOURCE' is not readable"
    exit 1
fi

# Write executing script:
cat > "$DEST" <<EOF
#!/bin/sh

# Detect dirname and change dir to prevent class not found errors.
if [ "\${0%/*}" != "\$0" ]; then
	cd "\${0%/*}"
fi

exec /usr/lib/swift-4.2.2-RELEASE-ubuntu18.04/usr/bin/swift "$MAINSOURCE" "\$@"
EOF
chmod a+x "$DEST"
exit 0
```

Getting this output:

```
[Mar 05 19:25:51.318] judgedaemon[1551]: API request GET executable
[Mar 05 19:25:51.410] judgedaemon[1551]: Unzipping
[Mar 05 19:25:51.417] judgedaemon[1551]: Compiling
[Mar 05 19:25:51.424] compile.sh[1683]: starting '/opt/domjudge/judgehost/lib/judge/compile.sh', PID = 1683
[Mar 05 19:25:51.425] compile.sh[1683]: arguments: '/opt/domjudge/judgehost/judgings/ip-172-31-95-162/endpoint-default/executable/swift/run' '/opt/domjudge/judgehost/judgings/ip-172-31-95-162/endpoint-default/c2-s15-j23'
[Mar 05 19:25:51.427] compile.sh[1683]: source file(s): hello.swift
[Mar 05 19:25:51.433] compile.sh[1683]: starting compile
[Mar 05 19:25:51.468] compile.sh[1683]: checking compilation exit-status
[Mar 05 19:25:51.473] compile.sh[1683]: exiting, code = '101'
[Mar 05 19:25:51.478] judgedaemon[1551]: Running compile.sh caused a runguard error/crash: 'runguard error - 13 - cannot start `%s''

--------------------------------------------------------------------------------

Compiling failed with exitcode 255, compiler output:
/opt/domjudge/judgehost/bin/runguard: cannot start `/opt/domjudge/judgehost/judgings/ip-172-31-95-162/endpoint-default/executable/swift/run': Permission denied
Try `/opt/domjudge/judgehost/bin/runguard --help' for more information.
```

**Comment by nickygerritsen** [comment]
Compilation happens outside the chariot, so the call to swiftc happens on the host OS. So you need swift outside the chroot as well.
Also swiftc can conpile into a binary right? Because then you could copy that binary to $DEST instead of having a shell wrapper that runs swift on the source code

**Comment by ashihCT** [comment]
I installed Swift on the host OS and verified it is working. 
Just for the sake of getting it to work, I paired the execution `run` file to:

```
#!/bin/sh
DEST="$1" ; shift
MEMLIMIT="$1" ; shift
MAINSOURCE="${ENTRY_POINT:-$1}"

# Check if entry point is valid
if [ ! -r "$MAINSOURCE" ]; then
    >&2 echo "error: main source file '$MAINSOURCE' is not readable"
    exit 1
fi

# Write executing script:
cat > "$DEST" <<EOF
#!/bin/sh

# Detect dirname and change dir to prevent class not found errors.
if [ "\${0%/*}" != "\$0" ]; then
	cd "\${0%/*}"
fi

exec /usr/lib/swift-4.2.2-RELEASE-ubuntu18.04/usr/bin/swift "$MAINSOURCE" "\$@"
EOF
chmod a+x "$DEST"
exit 0
```

I am getting the same error.
Not sure what ` 'runguard error - 13 - cannot start `%s''` means.

**Comment by nickygerritsen** [comment]
Maybe your `run` file is not executable?
Otherwise I need to dive into this but that will probably not be before Thursday

**Comment by ashihCT** [comment]
It seems like the run file's permission were not set properly. 
I had to go into the `endpoint-default/executable/swift` directory and do
`sudo chmod 755 run` and that solved the error.

Seems like I am getting closer, but getting a `run-error` now.

Giving a Program Error output.
`<unknown>:0: error: no such file or directory: 'hello.swift'`

**Comment by ashihCT** [comment]
Looks like I am getting a new error 
```
<unknown>:0: error: unable to open output file '/tmp/org.llvm.clang.1001/ModuleCache/2HC0E2D0KY7XR/SwiftShims-I0A71YSSMR2E.pcm': 'No such file or directory'
<unknown>:0: error: could not build C module 'SwiftShims'
```

I am at a loss as what is happening since this looks to be similar to the old issue #236. I ran a local copy of `hello.swift` in both the os and in CHROOT and it outputs just fine.

**Comment by nickygerritsen** [comment]
I think this can indeed be solved by building the swift code outside the chroot as it now needs a writable tmp directory, which it doesn’t have inside the chroot

**Comment by nickygerritsen** [comment]
I did some testing with the latest Swift download and I can compile it successfully, copy it to a machine without Swift and run it. This means Swift is *not* needed in the chroot if you compile before. Assuming you have `swiftc` in your path *outside* the chroot (which you can do by changing the `$PATH` variable before running the judgehost, this `run` should work:

```bash
#!/bin/sh

# Swift compile wrapper-script for 'compile.sh'.
# See that script for syntax and more info.

DEST="$1" ; shift
MEMLIMIT="$1" ; shift

# Add -DONLINE_JUDGE or -DDOMJUDGE below if you want it make easier for teams
# to do local debugging.

# -O:                 Optimizations (default for speed)
# -static-executable: Statically link the executable
# -static-stdlib:     Statically link the Swift standard library
swift -O -static-executable -static-stdlib test.swift -o "$DEST" "$@"
exit $?
```

This will only work if either:
* You only have one file
* Your main code is in main.swift

We can probably improve this script by doing something with `MAINSOURCE="${ENTRY_POINT:-$1}"`,  and checking if that is `main.swift`. If it is we do nothing. If it isn't, we check if a `main.swift` exists. If it does, we exit (because this is not allowed for Swift). If a main.swift file doesn't exist, we `mv $MAINSOURCE main.swift` and detect other swift files to pass to `swiftc`.

As this is probably useful for other people, I will work on this sometime soon so it will be in the main branch.

**Comment by ashihCT** [comment]
Thanks for the explanation, Nicky! Is there a setup that I am missing? 
I am still getting the error:
```
Compiling failed with exitcode 127, compiler output:
/opt/domjudge/judgehost/judgings/ip-172-31-86-71/endpoint-default/executable/swift/run: 15: /opt/domjudge/judgehost/judgings/ip-172-31-86-71/endpoint-default/executable/swift/run: swift: not found
```
Run file is setup:
<img width="553" alt="screen shot 2019-03-06 at 10 09 36 am" src="https://user-images.githubusercontent.com/42871040/53891460-6a567100-3ff8-11e9-8c2d-b582a5f98256.png">

I have access to Swiftc:
<img width="336" alt="screen shot 2019-03-06 at 10 06 39 am" src="https://user-images.githubusercontent.com/42871040/53891476-74786f80-3ff8-11e9-8737-ac6a84c3c31f.png">

I am able to access both swiftc by adding `/usr/local/bin/swift-4.2.3-RELEASE-ubuntu18.04/usr/bin ` to the `$PATH` by adding it to the` .bashrc`

**Comment by nickygerritsen** [comment]
No the `run` file runs it outside the chroot.

You can either:
* Use `/usr/local/bin/swift-4.2.3-RELEASE-ubuntu18.04/usr/bin/swift` instead of `swift` in the run file
* Edit `/etc/environment` to change PATH. I think this will work but I still need to check this

**Comment by ashihCT** [comment]
I tried adding it to `environment`. did not work. Using the full path in the run file worked for me.

It almost worked, but it's failing validation by the judge.
<img width="705" alt="screen shot 2019-03-06 at 10 52 24 am" src="https://user-images.githubusercontent.com/42871040/53894445-1d759900-3ffe-11e9-8d76-8bf519068ce7.png">

**Comment by nickygerritsen** [comment]
Woops, you need `swiftc` instead of `swift`. Also remove the hardcoded `test.swift` 😄  .

**Comment by ashihCT** [comment]
As always, you are the bomb! It's working.

I tried rebooting ubuntu and running it with just `swiftc` and it did not work.

**Comment by nickygerritsen** [comment]
> As always, you are the bomb! It's working.
Nice 😄 

> I tried rebooting ubuntu and running it with just `swiftc` and it did not work.
I will look into this. Probably creating a symlink in `/usr/bin/swiftc` to the actual `swiftc` location will also work.

When I'm done with creating and pushing a script I will type here what I did to get it working.

**Comment by ashihCT** [comment]
@nickygerritsen A side note in adding Swift to DOMJudge. I noticed every time that I modified an executable that hasn't been predefined, the permissions are set so the judge cannot execute "run" or "build". I would have to go into the endpoint `judgehost/judgings/ip-172-31-86-71/endpoint-default/executable/swift/run: 15: /opt/domjudge/judgehost/judgings/ip-172-31-86-71/endpoint-default/executable/` in the terminal and run `sudo CHMOD 755` on `run` and `build`. Anyway to not have to do this?

**Comment by nickygerritsen** [comment]
As said, I have just pushed Swift support 😄 .

What needs to be done to get it working:

* Download the swift `.tar.gz` somewhere and extract it.
* Install Swift dependencies: `sudo apt-get install clang libicu-dev`
* Create a symlink from `/usr/bin/swiftc` to `<swift-path>/usr/bin/swiftc` (or add `swiftc` to your path any other way

That's it, it then works.

I have also added some 'smart' autodetect logic for the main file:

* If a file `main.swift` exists, that will be the main file
* Otherwise the first file will be the main file. It will be renamed to `main.swift` to make `swiftc` happy
* If "require entrypoint" is turned on for Swift, the file you specified will be the main file. It will be renamed to `main.swift` (unless it is already named that way), but if a `main.swift` already exists, an error will be thrown.

The `swiftc` command does give two warnings when compiling (about `-pie` being unused and about the static binary still needing glibc) but I think these are harmless and I have no way to disable them.

**Comment by nickygerritsen** [comment]
> @nickygerritsen A side note in adding Swift to DOMJudge. I noticed every time that I modified an executable on the Jury interface that isn't part of the predefined set, the permissions are set so the judge cannot execute "run" or "build". I would have to go into the endpoint e.g.`/opt/domjudge/judgehost/judgings/ip-172-31-86-71/endpoint-default/executable/` in the terminal and run `sudo CHMOD 755` on `run` and `build`. Anyway to not have to do this?

How did you create this executable? I think you need to `chmod +x` *before* creating the zipfile that you upload to DOMjudge.

**Comment by ashihCT** [comment]
Thanks for the adding Swift support!

I create the executable using notepad and then compress it using the mac utility then uploaded via the web interface.

**Comment by nickygerritsen** [comment]
> Thanks for the adding Swift support!
> 
> I create the executable using notepad and then compress it using the mac utility then uploaded via the web interface.

Ah yes, then it indeed misses a `chmod +x`

**Comment by melongist** [comment]
Dear nickygerritsen

with.. your comments below,
...
> As said, I have just pushed Swift support 😄 .
> 
> What needs to be done to get it working:
> 
> * Download the swift `.tar.gz` somewhere and extract it.
> * Install Swift dependencies: `sudo apt-get install clang libicu-dev`
> * Create a symlink from `/usr/bin/swiftc` to `<swift-path>/usr/bin/swiftc` (or add `swiftc` to your path any other way
...


I made script to install swift complilation for ubuntu20.04 LTS server + DOMjudge 7.3.3
...
wget https://swift.org/builds/swift-5.4.2-release/ubuntu2004/swift-5.4.2-RELEASE/swift-5.4.2-RELEASE-ubuntu20.04.tar.gz
tar -zxvf swift-5.4.2-RELEASE-ubuntu20.04.tar.gz
sudo apt install -y clang libicu-dev
sudo ln -s ~/swift-5.4.2-RELEASE-ubuntu20.04/usr/bin/swiftc /usr/bin/swiftc
...

but... I've got Compilation unsuccesful ... COMPILER-ERROR below
...

<img width="1545" alt="swift" src="https://user-images.githubusercontent.com/7741650/132260094-8cbf9c8a-f2b6-472d-bb0e-83d1530a3c70.png">


How can I fix it... to compile swift? :)

Respectfully
Hyun-seok

**Comment by nickygerritsen** [comment]
I do not recognize this error and I do not have access to a machine to check in the next few weeks. Maybe someone else can check but otherwise it will be a while before I can get back to you

**Comment by melongist** [comment]
> I do not recognize this error and I do not have access to a machine to check in the next few weeks. Maybe someone else can check but otherwise it will be a while before I can get back to you

Thank you for your very fast reply~ :)

I'll keep to seek~ to solve this~ thank you~ :)

**Comment by melongist** [comment]
I did it! ... but...

...
#swift compiler installation for ubuntu 20.04
...
sudo apt -y install clang libicu-dev
wget https://swift.org/builds/swift-5.4.2-release/ubuntu2004/swift-5.4.2-RELEASE/swift-5.4.2-RELEASE-ubuntu20.04.tar.gz
tar -zxvf swift-5.4.2-RELEASE-ubuntu20.04.tar.gz
rm swift-5.4.2-RELEASE-ubuntu20.04.tar.gz
sudo mv ~/swift-5.4.2-RELEASE-ubuntu20.04 ~/swift
sudo ln -s ~/swift/usr/bin/swiftc /usr/bin/swiftc
...


#dj_make_chroot for swift
...
sudo /opt/domjudge/judgehost/bin/dj_make_chroot -i swift
...


#... reboot..

#Enable swift allow in admin page
#Enable swift submit in admin page


#but I've got 
 ... unable to open output file '/nonexistent/.cache/clang/ModuleCache/2D5SXEFBE4L5J/SwiftShims-33SS20R04BHPP.pcm': 'Permission denied'

<img width="1440" alt="permissiondenied" src="https://user-images.githubusercontent.com/7741650/134140539-413756f6-2a0e-4b33-835e-0e758c8ff5c7.png">


So... 

#... make /nonexistent directory manually?
Temporarily, I created /nonexistent directory manually by typing the terminal command, then I gave it permission 757 like below. 

`sudo mkdir /nonexistent`
`sudo chmod 757 /nonexistent`

<img width="1440" alt="ivegotswift" src="https://user-images.githubusercontent.com/7741650/134140361-0e0f0c81-3c9f-41fd-a25e-7fca73383299.png">

So it was compiled and judgged! But, is there a more fundamental way to enable to submit and judge swift? :)

**Comment by LETS-BEE** [comment]
Hi. I think I have solved this problem.

In swift script, you just add '-module-cache-path "./" ' compiler option.
Or any directory if you want.

So code is...
`swiftc -O -module-cache-path ./ -static-executable -static-stdlib -o "$DEST" $SOURCES `

**Comment by LETS-BEE** [comment]
> 
> 
> Sounds like we can put this in the default Swift script?

yes, we change default Swift script.

**Comment by melongist** [comment]
Thank you~ all!! :)
